quotes = [
    "Blank",
    "“Courage doesn't always roar. Sometimes courage is a quiet voice at the end of the day saying, “I will try again tomorrow.”” —Mary Anne Radmacher",
    "“Alone we can do so little, together we can do so much.” — Helen Keller",
    "“Ihminen on lapsi, hautaan asti” —Aivovuoto. Roughly translated from Finnish to English, “Human being is child till the grave”",
    "“Numbing the pain for a while will make it worse when you finally feel it.” —Albus Dumbledore from Harry Potter and the Goblet of Fire",
    "“The battles that count aren't the ones for gold medals. The struggles within yourself—the invisible, inevitable battles inside all of us—that's where it's at.” —Jesse Owens",
    "“Someone will declare, “I am the leader!” and expect everyone to get in line and follow him or her to the gates of heaven or hell. My experience is that it doesn’t happen that way. Others follow you based on the quality of your actions rather than the magnitude of your declarations.” ―Bill Walsh",
    "“Get a good idea and stay with it. Dog it, and work at it until it’s done right.” —Walt Disney",
    "“I am not a product of my circumstances. I am a product of my decisions.” — Stephen R. Covey",
    "“There’s a lot of beauty in ordinary things. Isn’t that kind of the point?” —Pam Beesly from The Office",
    "“Show up, show up, show up, and after a while the muse shows up, too.” —Isabel Allende",
    "“Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together.”—Diane McLaren",
    "“Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it.” — Steve Jobs",
    "“Use your smile to change the world; don’t let the world change your smile.”",
    "“We don’t rise to the level of our expectations, we fall to the level of our training.” —David Goggins",
    "“Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.” – Wayne Dyer",
    "“There is no better way to grow as a person than to do everyday something you hate.” —David Goggins",
    "“Magic Mirror on the wall, who is the fairest one of all?” -Snow White and the Seven Dwarfs, 1937",
    "“They may take our lives, but they'll never take our freedom” -Braveheart, 1995",
    "“The only thing more contagious than a good attitude is a bad one.” —David Goggins",
    "“Houston, we have a problem.” -Apollo 13, 1995",
    "“I always wanted to be somebody, but now I realise I should have been more specific.” — Lily Tomlin",
    "“A year from now you will wish you had started today.” —Unknown",
    "“If the highest aim of a captain were to preserve his ship, he would keep it in port forever.” —Thomas Aquinas",
    "“Worry is a misuse of imagination.” —Unknown",
    "“Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable.” —John Wooden",
    "“Just one small positive thought in the morning can change your whole day.” — Dalai Lama",
    "“You can never leave footprints that last if you are always walking on tiptoe.” —Leymah Gbowee",
    "“Small is not just a stepping-stone. Small is a great destination itself.” ―Jason Fried",
    "“I'm the king of the world!” -Titanic, 1997",
    "“Success is not final; failure is not fatal: It is the courage to continue that counts.” — Winston S. Churchill",
    "“Never let people who choose the path of least resistance steer you away from your chosen path of most resistance.” —David Goggins",
    "“The elevator to success is out of order. You’ll have to use the stairs, one step at a time.” — Joe Girard",
    "“As a single footstep will not make a path on the earth, so a single thought will not make a pathway in the mind. To make a deep physical path, we walk again and again. To make a deep mental path, we must think over and over the kind of thoughts we wish to dominate our lives.” —Henry David Thoreau",
    "“Pain unlocks a secret doorway in the mind, one that leads to both peak performance, and beautiful silence.” —David Goggins",
    "“When you give joy to other people, you get more joy in return . You should give a good thought to happiness that you can give out.”— Eleanor Roosevelt",
    "“You cannot plow a field by turning it over in your mind. To begin, begin.” ―Gordon B. Hinckley",
    "“Be a positive energy trampoline – absorb what you need and rebound more back.” — Dave Carolan",
    "“It’s not the will to win that matters—everyone has that. It’s the will to prepare to win that matters.” —Paul Bryant",
    "“The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.” — William James",
    "“The path to success will leave you callused, bruised, and very tired. It will also leave you empowered.” —David Goggins",
    "“Fear of what other people will think is the single most paralyzing dynamic in business and in life. The best moment of my life was the day I realized that I no longer give a damn what anybody thinks. That’s enormously liberating and freeing, and it’s the only way to live your life and do your business” — Cindy Gallop",
    "“Just keep swimming.” -Finding Nemo, 2003",
    "“Great spirits have always encountered violent opposition from mediocre minds. The mediocre mind is incapable of understanding the man who refuses to bow blindly to conventional prejudices and chooses instead to express his opinions courageously and honestly” —Albert Einstein",
    "“If you choose to do something, attack it.” —David Goggins",
    "“Here's to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes. The ones who see things differently. They're not fond of rules. And they have no respect for the status quo. You can quote them, disagree with them, glorify or vilify them. About the only thing you can't do is ignore them. Because they change things. They push the human race forward. And while some may see them as the crazy ones, we see genius. Because the people who are crazy enough to think they can change the world, are the ones who do.” ―Rob Siltanen",
    "“When you change your thoughts, remember to also change your world.”—Norman Vincent Peale",
    "“Greatness pulls mediocrity into the mud. Get out there and get after it.” —David Goggins",
    "“Life is like riding a bicycle. To keep your balance you must keep moving.” —Albert Einstein",
    "“The thing women have yet to learn is nobody gives you power. You just take it. ” ― Roseanne Barr",
    "“Gordie: Do you think I'm weird?\nChris: Definitely.\nGordie: No man, seriously. Am I weird?\nChris: Yeah, but so what? Everybody's weird.” —Stand by Me",
    "“Dobby is free.” —Dobby from Harry Potter and the Chamber of Secrets",
    "“Sometimes magic is just someone spending more time on something than anyone else might reasonably expect.” —Raymond Joseph Teller",
    "“What you do speaks so loudly that I cannot hear what you say.” —Ralph Waldo Emerson",
    "“Don't bunt. Aim out of the ballpark. Aim for the company of immortals.” ―David Ogilvy",
    "“A martini. Shaken, not stirred.” -Goldfinger, 1964",
    "“Every strike brings me closer to the next home run.” — Babe Ruth",
    "“All our dreams can come true, if we have the courage to pursue them.” —Walt Disney",
    "“Setting goals is the first step in turning the invisible into the visible.” — Tony Robbins",
    "“Perfection is not attainable. But if we chase perfection we can catch excellence.” —Vince Lombardi",
    "“If you really want to do something, you'll find a way. If you don't, you'll find an excuse.” ―Jim Rohn",
    "“The heart keeps getting broken until it stays open” —Thundercat",
    "“When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love…” – Marcus Aurelius",
    "“To infinity and beyond!” -Toy Story, 1995",
    "“Be more than motivated, be more than driven, become literally obsessed to the point where people think you’re f*cking nuts.” —David Goggins",
    "“If you change the way you look at things, the things you look at change.” — Wayne Dyer",
    "“Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.” — Alexander Graham Bell",
    "“People often say that motivation doesn’t last. Well, neither does bathing – that’s why we recommend it daily.” — Zig Ziglar",
    "“It is our choices, Harry, that show what we truly are, far more than our abilities.” ―Albus Dumbledore from Harry Potter and the Chamber of Secrets",
    "“Start where you are. Use what you have. Do what you can.” — Arthur Ashe",
    "“Chris: I'm never gonna get out of this town. Am I, Gordie?\nGordie: You can do anything you want, man.\nChris: Yeah, sure. Give me some skin.\nGordie: I'll see ya.\nChris: Not if I see you first.” —Stand by Me",
    "“I am your father.” -Star Wars Episode V: The Empire Strikes Back, 1980",
    "“Make sure your worst enemy doesn’t live between your own two ears.” —Laird Hamilton",
    "“You can get everything in life you want if you will just help enough other people get what they want.” —Zig Ziglar",
    "“Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.” —Earl Nightingale",
    "“Bloom where you are planted”",
    "“It is a rough road that leads to the heights of greatness.” —Lucius Annaeus Seneca",
    "“Young Warden: I'm tired of this, Grandpa...\nTrout Walker: [shouts] Well, that's too damn bad! You keep digging!\nYoung Warden: Well, excuse me.” —Holes",
    "“And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.” —Anaïs Nin",
    "“Failure is simply the opportunity to begin again, this time more intelligently.” — Henry Ford",
    "“I can’t tell you how many times I’ve been given a no. Only to find that a better, brighter, bigger yes was right around the corner.” — Arlan Hamilton",
    "“Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.” —Earl Nightingale",
    "“The standard you walk past, is the standard you accept.” —David Hurley",
    "“Denial is the ultimate comfort zone.” —David Goggins",
    "“Don't let someone else's opinion of you become your reality” — Les Brown",
    "“It is the quality of one’s convictions that determines success, not the number of followers.” —Remus Lupin from Harry Potter and the Deathly Hallows",
    "“If you believe something needs to exist, if it's something you want to use yourself, don't let anyone ever stop you from doing it.” —Tobias Lütke",
    "“Education is the most powerful weapon which you can use to change the world.” — Nelson Mandela",
    "“Do not stop thinking of life as an adventure. You have no security unless you can live bravely, excitingly, imaginatively; unless you can choose a challenge instead of competence.” ―Eleanor Roosevelt",
    "“There is a vitality, a life force, an energy, a quickening that is translated through you into action, and because there is only one of you in all time, this expression is unique. And if you block it, it will never exist through any other medium and will be lost.” ―Martha Graham",
    "“I wish there was a way to know you're in the good old days before you've actually left them.” —Andy Bernard from The Office",
    "“You cannot swim for new horizons until you have courage to lose sight of the shore.” —William Faulkner",
    "“In order to be irreplaceable one must always be different.” —Coco Chanel",
    "“I solemnly swear that I am up to no good.” ―Harry Potter from Harry Potter and the Prisoner of Azkaban",
    "“Crikey, mate. You’re far safer dealing with crocodiles and western diamondback rattlesnakes than the executives and the producers and all those sharks in the big MGM building.” —Steve Irwin",
    "“Life is like a sewer… what you get out of it depends on what you put into it.” — Tom Lehrer",
    "“Somewhere, something incredible is waiting to be known.” —Carl Sagan",
    "“It is never too late to be what you might have been.” — George Eliot",
    "“We all need small sparks, small accomplishments in our lives to fuel the big ones […] Because its the small sparks, which start small fires, that eventually build enough heat to burn the whole f*cking forest down.” —David Goggins",
    "“Keep your friends close, but your enemies closer.” -The Godfather Part II, 1974",
    "“For the great doesn’t happen through impulse alone, and is a succession of little things that are brought together.” —Vincent van Gogh",
    "“I learned a long time ago that there is something worse than missing the goal, and that’s not pulling the trigger.” —Mia Hamm",
    "“Toto, I've a feeling we're not in Kansas anymore.” -The Wizard of Oz, 1939",
    "“We must reach out our hand in friendship and dignity both to those who would befriend us and those who would be our enemy.” — Arthur Ashe",
    "“Do not pity the dead, Harry. Pity the living, and , above all, those who live without love.” ―Albus Dumbledore from Harry Potter and the Deathly Hallows",
    "“Fasten your seatbelts. It's going to be a bumpy night.” -All About Eve, 1950",
    "“Never let success get to your head and never let failure get to your heart.” —Drake",
    "“You’re the smartest guy I’ve ever met. And you’re too stupid to see… he made up his mind ten minutes ago.” —Hank Schrader from Breaking Bad",
    "“Be the change that you wish to see in the world.” ―Mahatma Gandhi",
    "“Sam: I can fix that.”\n[repeated line] —Holes",
    "“Some people want it to happen, some wish it would happen, others make it happen.” —Michael Jordan",
    "“I believe that education is all about being excited about something. Seeing passion and enthusiasm helps push an educational message.” —Steve Irwin",
    "“You carry the passport to your own happiness.” —Diane von Furstenberg",
    "“People say nothing is impossible, but I do nothing every day.” — Winnie the Pooh",
    "“You're gonna need a bigger boat.” -Jaws, 1975",
    "“If the decisions you make about where you invest your blood, sweat, and tears are not consistent with the person you aspire to be, you’ll never become that person.” ―Clayton M. Christensen",
    "“You either have 99 problems or a health problem”",
    "“We are what we repeatedly do. Excellence, then, is not an act, but a habit.” — Aristotle",
    "“The only way of discovering the limits of the possible is to venture a little way past them into the impossible.” ―Arthur C. Clarke",
    "“Hustle beats talent when talent doesn’t hustle” – Ross Simmonds",
    "“I have stood on a mountain of no’s for one yes.” —Barbara Elaine Smith",
    "“From the time you take your first breath, you become eligible to die. You also become eligible to find your greatness and become the one warrior” —David Goggins",
    "“Inconceivable!” -The Princess Bride, 1987",
    "“Doubt is a killer. You just have to know who you are and what you stand for .” —Jennifer Lopez",
    "“It's fine to celebrate success but it is more important to heed the lessons of failure.” — Bill Gates",
    "“You’ll find that education is just about the only thing lying around loose in this world, and it’s about the only thing a fellow can have as much of as he’s willing to haul away.” —John Graham",
    "“I invite everyone to choose forgiveness rather than division, teamwork over personal ambition.” — Jean-Francois Cope",
    "“Be yourself everyone else is already taken.” ―Oscar Wilde",
    "“You are trouble. I’m sorry the kid here doesn’t see it, but I sure as hell do. You are a time bomb. Tick tick ticking. And I have no intention for being around for the boom.” —Mike Ehrmantraut from Breaking Bad",
    "“The question isn't who is going to let me; it's who is going to stop me.” — Ayn Rand",
    "“If you tell the truth, you don't have to remember anything.” ―Mark Twain",
    "“There's no place like home.” -The Wizard of Oz, 1939",
    "“If you have the opportunity to play this game called life, you have to appreciate every moment. A lot of people don't appreciate their moment until it's passed” —Kanye West",
    "“Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness.” — Oprah Winfrey",
    "“Tell yourself the truth! That you’ve wasted enough time, and that you have other dreams that will take courage to realize, so you don’t die a f*cking pussy.” —David Goggins",
    "“Resilience is when you address uncertainty with flexibility.” —Unknown",
    "“Mr. Sir: I got a story for your Girl Scouts. Once upon a time there was a magical place where it never rained. The end.”\n[snickers scornfully] —Holes",
    "“Winners focus on winning. Losers focus on winners”",
    "“What you do makes a difference, and you have to decide what kind of difference you want to make.” —Jane Goodall",
    "“Meredith, I’m worried that the baby thinks people can’t change.” ―Tim Robinson from I Think You Should Leave with Tim Robinson",
    "“I have never let my schooling interfere with my education.” —Mark Twain",
    "“You’re killin’ me, Smalls.” -The Sandlot, 1993",
    "“I am the danger. A guy opens his door and gets shot, and you think that of me? No... I am the one who knocks!” —Walter White from Breaking Bad",
    "“Fools talk, cowards are silent, wise men listen.” —Carlos Ruiz Zafon",
    "“Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.” ―Martin Luther King Jr.",
    "“It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest.” —Walter Anderson",
    "“To know how much there is to know is the beginning of learning to live.” —Dorothy West",
    "“Don’t let potential be written on your tombstone”",
    "“It's alive! It's alive!” -Frankenstein, 1931",
    "“Aragorn : What do you fear, my lady?\nEowyn : A cage. To stay behind bars until use and old age accept them and all chance of valor has gone beyond recall or desire.” —From The Lord of the Rings: The Two Towers",
    "“I don’t stop when I’m tired, I stop when I’m done.” —David Goggins",
    "“I was everyone I'd ever met who I never loved enough” —Robert DeLong",
    "“Learn as if you will live forever, live like you will die tomorrow.” — Mahatma Gandhi",
    "“Discipline, doing what you hate to do, but nonetheless doing it like you love it.” —Mike Tyson",
    "“You can be the ripest, juiciest peach in the world, and there's still going to be somebody who hates peaches.” —Dita Von Teese",
    "“Keep a little fire burning;however small, however hidden.” ―Cormac McCarthy",
    "“If it makes you nervous, you’re doing it right.” —Childish Gambino",
    "“If you can't explain it simply, you don't understand it well enough.” —Albert Einstein",
    "“We can see through others only when we can see through ourselves.” – Bruce Lee",
    "“The chains of habit are too light to be felt until they are too heavy to be broken.”",
    "“Mental toughness is a lifestyle.” —David Goggins",
    "“Nature does not hurry, yet everything is accomplished” —Lao Tzu",
    "“It’s not about better time management. It’s about better life management” — Alexandra of The Productivity Zone",
    "“I've searched all the parks in all the cities and found no statues of committees.” —Gilbert K. Chesterton",
    "“Your Monday morning thoughts set the tone for your whole week. See yourself getting stronger, and living a fulfilling, happier & healthier life.” – Germany Kent",
    "“You want to be uncommon amongst uncommon people. Period.” —David Goggins",
    "“Hasta la vista, baby.” -Terminator 2: Judgment Day, 1991",
    "“It is remarkable how much long-term advantage people like us have gotten by trying to be consistently not stupid, instead of trying to be very intelligent.” —Charlie Munger",
    "“It’s possible to transcend anything that doesn’t kill you.” —David Goggins",
    "“I am so clever that sometimes I don’t understand a single word of what I am saying.” — Oscar Wilde",
    "“These violent delights have violent ends” —Friar Lawrence from Romeo & Juliet/Westworld",
    "“Dumbledore watched her fly away, and as her silvery glow faded he turned back to Snape, and his eyes were full of tears. ‘After all this time?’ ‘Always, ’” ―Snape from Harry Potter and the Deathly Hallows",
    "“Someone's sitting in the shade today because someone planted a tree a long time ago.” —Warren Buffet",
    "“Teamwork is the ability to work together toward a common vision. The ability to direct individual accomplishments toward organizational objectives. It is the fuel that allows common people to attain uncommon results.” — Andrew Carnegie",
    "“You’ll never get bored when you try something new. There’s really no limit to what you can do.” — Dr. Seuss",
    "“Very few people know how the bottom feels, but I do. It’s like quicksand. It grabs you, sucks you under, and won’t let go. When life is like that it’s easy to drift and continue to make the same comfortable choices that are killing you, over and over again.” —David Goggins",
    "“You talking to me?” -Taxi Driver, 1976",
    "“If you’re not positive energy, you’re negative energy.” Mark Cuban",
    "“Don’t focus on what you think you deserve. Take aim at what you are willing to earn.” —David Goggins",
    "“You can't handle the truth!” -A Few Good Men, 1992",
    "“A surplus of effort could overcome a deficit of confidence.” —Sonia Sotomayor",
    "“Do not wait for the perfect time and place to enter, for you are already onstage.” —Unknown",
    "“The only one who can tell you ““you can’t win” is you and you don’t have to listen.” —Jessica Ennis",
    "“Take the attitude of a student, never be too big to ask questions, never know too much to learn something new.” —Augustine Og Mandino",
    "“Only you can master your mind, which is what it takes to live a bold life filled with accomplishments most people consider beyond their capability.” —David Goggins",
    "“And, you know, money, money's great. I can't get enough money and you know what I'm going to do with it? I'm going to buy wilderness areas with it. Every single cent I get goes into conservation”  —Steve Irwin",
    "“Frodo: I can't do this, Sam.\nSam: I know. It's all wrong. By rights we shouldn't even be here. But we are. It's like in the great stories, Mr. Frodo. The ones that really mattered. Full of darkness, and danger, they were. And sometimes you didn't want to know the end, because how could the end be happy? How could the world go back to the way it was when so much bad had happened? But in the end, it's only a passing thing, this shadow. Even darkness must pass. A new day will come. And when the sun shines, it'll shine out the clearer. Those were the stories that stayed with you. That meant something. Even if you were too small to understand why. But I think, Mr. Frodo, I do understand. I know now. Folk in those stories had lots of chances of turning back only they didn't. They kept going. Because they were holding on to something.\nFrodo: What are we holding on to, Sam?\nSam: That there's some good in this world, Mr. Frodo...and it's worth fighting for.”  —The Lord of the Rings: The Two Towers",
    "“I never had any friends later on like the ones I had when I was twelve. Jesus, does anyone?” —Stand by Me",
    "“Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. The slogan 'Press On' has solved and always will solve the problems of the human race.” —Calvin Coolidge",
    "“Life can be much broader once you discover one simple fact: Everything around you that you call life was made up by people that were no smarter than you. And you can change it, you can influence it… Once you learn that, you'll never be the same again.” —Steve Jobs",
    "“My friends don't understand we all are lost” —Mondo Cozmo",
    "“E.T. phone home.” -E.T. the Extra-Terrestrial, 1982",
    "“When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.” — Henry Ford",
    "“The only thing necessary for the triumph of evil is for good men to do nothing”",
    "“Our greatest glory is not in never falling, but in rising every time we fall.” — Confucius",
    "“If you’re willing to suffer, and I mean suffer, your brain and body once connected together, can do anything.” —David Goggins",
    "“A witty woman is a treasure; a witty beauty is a power.” ― George Meredith",
    "“If everything you try works, you aren't trying hard enough.” —Gordon Moore",
    "“You've got to get up every morning with determination if you're going to go to bed with satisfaction.” — George Lorimer",
    "“May the Force be with you.” -Star Wars, 1977",
    "“You learn more from failure than from success. Don’t let it stop you. Failure builds character.” — Unknown",
    "“Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.” ―Bernard M. Baruch",
    "“I think it’s intoxicating when somebody is so unapologetically who they are.” —Don Cheadle",
    "“I have not failed. I've just found 10,000 ways that won't work.” — Thomas A. Edison",
    "“A day may come when the courage of men fails when we forsake our friends and break all bonds of fellowship. But it is not this day. An hour of wolves and shattered shields, when the age of men comes crashing down. But it is not this day. This day we fight.” –Aragorn from The Lord of the Rings: The Return of the King",
    "“I will not lose, for even in defeat, there’s a valuable lesson learned, so it evens up for me.” —Jay-Z",
    "“We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success.” — Ariana Huffington",
    "“No one changes the world who isn’t obsessed.” —Billie Jean King",
    "“My mama always said life was like a box of chocolates. You never know what you're gonna get.” -Forrest Gump, 1994",
    "“The road to success and the road to failure are almost exactly the same.” — Colin R. Davis",
    "“Remember, teamwork begins by building trust. And the only way to do that is to overcome our need for invulnerability.” — Patrick Lencioni",
    "“A wizard is never late, Frodo Baggins. Nor is he early; he arrives precisely when he means to.” —Gandalf from The Lord of the Rings: The Fellowship of the Ring",
    "“Opportunity is missed by most people because it is dressed in overalls and looks like work.” — Thomas Edison",
    "“It is better to fail in originality than to succeed in imitation.” — Herman Melville",
    "“Love your family, work super hard, live your passion.” — Gary Vaynerchuk",
    "“Even extraordinary people, and I believe you are, are driven by human banalities” —Tyrell Wellick from Mr. Robot",
    "“Don’t worry about failure; you only have to be right once.” —Drew Houston",
    "“All love that has not friendship for its base, is like a mansion built upon sand.” —Ella Wheeler Wilcox",
    "“Education is the most powerful weapon which you can use to change the world.” — Nelson Mandela",
    "“Talent wins games, but teamwork and intelligence win championships.” — Michael Jordan",
    "“Opportunities don't happen, you create them.” — Chris Grosser",
    "“People underestimate the power of nostalgia. Nostalgia is truly one of the greatest human weaknesses... second only to the neck.” —Dwight Schrute from The Office",
    "“Relentlessly prune bullshit, don't wait to do things that matter, and savor the time you have. That's what you do when life is short.” —Paul Graham",
    "“Some women choose to follow men, and some choose to follow their dreams. If you’re wondering which way to go, remember that your career will never wake up and tell you that it doesn’t love you anymore.” — Lady Gaga",
    "“There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind.” —Mister Rogers",
    "“I’d rather regret the things I’ve done than regret the things I haven’t done.” —Lucille Ball",
    "“Ideation without execution is delusion.” — Robin Sharma",
    "“I’m a greater believer in luck, and I find the harder I work the more I have of it.” — Thomas Jefferson",
    "“The greater the difficulty, the more the glory in surmounting it.” ―Epicurus",
    "“Success is getting what you want, happiness is wanting what you get.” ―W. P. Kinsella",
    "“When we strive to become better than we are, everything around us becomes better too.” — Paulo Coelho",
    "“He that can have patience can have what he will.” ―Benjamin Franklin",
    "“Where you invest your love, you invest your life” —Mumford & Sons",
    "“True freedom is impossible without a mind made free by discipline.” ―Mortimer J. Adler",
    "“Don’t let yesterday take up too much of today.” — Will Rogers",
    "“Fear is like a fire. If you can control it, it can cook for you. It can heat your house. If you can't control it, it will burn everything around you and destroy you. Fear is your friend and your worst enemy” —Sui Ishida",
    "“Nothing ever goes away until it teaches us what we need to know.” – Pema Chodron",
    "“Bond. James Bond.” -Dr. No, 1962",
    "“If you can't yet do great things, do small things in a great way.” ―Napoleon Hill",
    "“Coming together is a beginning. Keeping together is progress. Working together is success.” — Henry Ford",
    "“Experience is a hard teacher because she gives the test first, the lesson afterwards.” ―Vernon Sanders Law",
    "“More is lost by indecision than wrong decision.” —Marcus Tullius Cicero",
    "“If you don’t like the road you’re walking, start paving another one.” —Dolly Parton",
    "“I choose to make the rest of my life the best of my life.” —Louise Hay",
    "“If you don’t risk anything, you risk even more.” —Erica Jong",
    "“First forget inspiration. Habit is more dependable. Habit will sustain you whether you're inspired or not. Habit will help you finish and polish your stories. Inspiration won't. Habit is persistence in practice.” ―Octavia Butler",
    "“No one is going to come help you. No one’s coming to save you.” —David Goggins",
    "“If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.” — Steve Jobs",
    "“Anything can make me stop and look and wonder, and sometimes learn.” —Kurt Vonnegut",
    "“It is a curious thing, Harry, but perhaps those who are best suited to power are those who have never sought it. Those who, like you, have leadership thrust upon them, and take up the mantle because they must, and find to their own surprise that they wear it well.” —Albus Dumbledore from Harry Potter and the Deathly Hallows",
    "“Give a man a gun and he can rob a bank, but give a man a bank, and he can rob the world.” —Tyrell Wellick from Mr. Robot",
    "“Everything you've ever wanted is sitting on the other side of fear.” — George Addair",
    "“Courage is like a muscle. We strengthen it by use.” —Ruth Gordon",
    "“You cannot always control what goes on outside. But you can always control what goes on inside.” — Wayne Dyer",
    "“Individual commitment to a group effort—that is what makes a team work, a company work, a society work, a civilisation work.” — Vince Lombardi",
    "“When we lose our principles, we invite chaos” —Irving from Mr. Robot",
    "“Either you run the day or the day runs you.” — Jim Rohn",
    "“I'll be back.” -The Terminator, 1984",
    "“Xehanort, you're so caught up in finding the shadows, you forgot about the light that cast them.” — Sora from Kingdom Hearts III",
    "“You have to build calluses on your brain just like how you build calluses on your hands. Callus your mind through pain and suffering.” —David Goggins",
    "“Life is one big tug of war between mediocrity and trying to find your best self.” —David Goggins",
    "“We don’t own the planet Earth, we belong to it. And we must share it with our wildlife.” —Steve Irwin",
    "“One of the differences between some successful and unsuccessful people is that one group is full of doers, while the other is full of wishers.” — Edmond Mbiaka",
    "“We’re either getting better or we’re getting worse.” —David Goggins",
    "“I never look back, darling. It distracts from the now.” —Edna Mode",
    "“If there is no struggle, there is no progress.” —Frederick Douglass",
    "“I'm not superstitious but I'm a little stitious.” —Michael Scott from The Office",
    "“The most common way people give up their power is by thinking they dont have any” —Alice Walker",
    "“Roads? Where we're going we don't need roads.” -Back to the Future, 1985",
    "“Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too.” — Mark Twain",
    "“Take your victories, whatever they may be, cherish them, use them, but don’t settle for them.” —Mia Hamm",
    "“The two most important days in your life are the day you’re born and the day you find out why.” – Mark Twain",
    "“You know you're in love when you can't fall asleep because reality is finally better than your dreams.” ―Dr. Seuss",
    "“My precious.” -The Lord of the Rings: Two Towers, 2002",
    "“Success usually comes to those who are too busy looking for it.” — Henry David Thoreau",
    "“Nobody cares what you did yesterday. What have you done today to better yourself?” —David Goggins",
    "“For every minute you are angry you lose sixty seconds of happiness.” ―Ralph Waldo Emerson",
    "“People's passion and desire for authenticity is strong.” —Constance Wu",
    "“The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.” — Winston Churchill",
    "“Hate. A little bit's okay. As long as you never forget who's boss.” —Don Eladio Vuente from Better Call Saul",
    "“Don't settle for average. Bring your best to the moment. Then, whether it fails or succeeds, at least you know you gave all you had.” —Angela Bassett",
    "“True humility is not thinking less of yourself; it is thinking of yourself less.” — C.S. Lewis",
    "“Don't let perfect be the enemy of good”",
    "“Goal setting is the secret to a compelling future.” — Tony Robbins",
    "“Live out of your imagination, not your history.” —Stephen Covey",
    "“Rivers know this: there is no hurry. We shall get there some day.” ―A.A. Milne",
    "“Here's Johnny!” -The Shining, 1980",
    "“Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.” —Dale Carnegie",
    "“Keep your eyes on the stars, and your feet on the ground.” ―Theodore Roosevelt",
    "“Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.” ―Maya Angelou",
    "“Two things are infinite: the universe and human stupidity and I'm not sure about the universe.” ―Albert Einstein",
    "“The reason we struggle with insecurity is because we compare our behind-the-scenes with everyone else’s highlight reel.” —Steve Furtick",
    "“Your Monday morning thoughts set the tone for your whole week. See yourself getting stronger, and living a fulfilling, happier & healthier life.” –Germany Kent",
    "“Because you might as well be dead. Seriously, if you always put limits on what you can do, physical or anything else, it’ll spread over into the rest of your life. It’ll spread into your work, into your morality, into your entire being. There are no limits. There are plateaus, but you must not stay there, you must go beyond them. If it kills you, it kills you. A man must constantly exceed his level.” —Bruce Lee",
    "“You are in danger of living a life so comfortable and soft, that you will die without ever realizing your true potential.” —David Goggins",
    "“A warrior is a guy that goes, ‘Im here again today. I’ll be here again tomorrow and the next day.’ It’s a person who puts no limit on what’s possible.” —David Goggins",
    "“The world is a dangerous place, Elliott, not because of those who do evil, but because of those who look on and do nothing” —Mr. Robot from Mr. Robot",
    "“If we take care of the moments, the years will take care of themselves.” —Maria Edgeworth",
    "“The most difficult thing is the decision to act, the rest is merely tenacity.” —Amelia Earhart",
    "“Mondays are the start of the work week which offer new beginnings 52 times a year!” – David Dweck",
    "“The best way out is always through.” ―Robert Frost",
    "“I'm not upset that you lied to me, I'm upset that from now on I can't believe you.” ―Friedrich Nietzsche",
    "“Inspiration does exist, but it must find you working.” —Pablo Picasso",
    "“Be sure you put your feet in the right place, then stand firm.” ―Abraham Lincoln",
    "“You can’t be that kid standing at the top of the waterslide, overthinking it. You have to go down the chute.” —Tina Fey",
    "“If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.” —Sirius Black from Harry Potter and the Goblet of Fire",
    "“Running away from a problem only increases the distance from the solution”",
    "“Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.” —Michael Scott from The Office",
    "“Success is stumbling from failure to failure with no loss of enthusiasm.” ―Winston Churchill",
    "“I do not try to dance better than anyone else . I only try to dance better than myself.” —Arianna Huffington",
    "“Don't look at your feet to see if you are doing it right. Just dance.” ―Anne Lamott",
    "“If we don’t mark the milestones, we’re just passing with the time.” —Lara Axelrod",
    "“You had me at ‘hello.’” —Jerry Maguire, 1996",
    "“Achieve more in failure than most do in success”",
    "“The homework doesn’t guarantee anything; with luck, it gives you a shot at something real.” —Bryan Cranston from A Life in Parts",
    "“Dost thou love life? Then do not squander time, for that is the stuff life is made of.” —Benjamin Franklin",
    "“It is not how much we have, but how much we enjoy, that makes happiness.” —Charles Spurgeon",
    "“An ounce of action is worth a ton of theory.” —Friedrich Engels",
    "“You cannot have a positive life and a negative mind.” —Joyce Meyer",
    "“Picture yourself vividly as winning and that alone will contribute immeasurably to success.” —Harry Emerson Fosdick",
    "“The charity that hastens to proclaim its good deeds, ceases to be charity, and is only pride and ostentation.” —William Hutton",
    "“To find joy in work is to discover the fountain of youth.” —Pearl S. Buck",
    "“The proper function of man is to live, not to exist. I shall not waste my days in trying to prolong them. I shall use my time.” —Jack London",
    "“Striving for excellence motivates you; striving for perfection is demoralizing.” —Harriet Braiker",
    "“Everybody can do something that makes a difference.” —Todd R. Wagner",
    "“Every moment of one's existence one is growing into more or retreating into less. One is always living a little more or dying a little bit.” —Norman Mailer",
    "“Everything has beauty, but not everyone sees it.” —Confucius",
    "“A mans life is interesting primarily when he has failed. I well know. For its a sign that he tried to surpass himself.” —Georges Clemenceau",
    "“It is almost impossible to throw dirt on someone without getting a little on yourself.” —Abigail Van Buren",
    "“Nothing will work unless you do.” —Maya Angelou",
    "“All love that has not friendship for its base, is like a mansion built upon sand.” —Ella Wheeler Wilcox",
    "“If we have no peace, it is because we have forgotten that we belong to each other.” —Mother Teresa",
    "“Life isn't fair, it's just fairer than death, that's all.” —William Goldman",
    "“All that we send into the lives of others comes back into our own.” —Edwin Markham",
    "“Life is 10 percent what happens to you and 90 percent how you react to it.” —Charles R. Swindoll",
    "“When your values are clear to you, making decisions becomes easier.” —Roy E. Disney",
    "“Courage faces fear and thereby masters it. Cowardice represses fear and is thereby mastered by it.” —Martin Luther King, Jr.",
    "“If you're not making mistakes, then you're not doing anything. I'm positive that a doer makes mistakes.” —John Wooden",
    "“Let how you live your life stand for something, no matter how small and incidental it may seem.” —Jodie Foster",
    "“As for the future, your task is not to foresee it, but to enable it.” —Antoine de Saint-Exupery",
    "“Big shots are only little shots who keep shooting.” —Christopher Morley",
    "“It takes as much energy to wish as it does to plan.” —Eleanor Roosevelt",
    "“Getting in touch with your true self must be your first priority.” —Tom Hopkins",
    "“Good temper, like a sunny day, sheds a ray of brightness over everything” —Washington Irving",
    "“Kindness is more important than wisdom, and the recognition of this is the beginning of wisdom.” —Theodore Isaac Rubin",
    "“It's good to have money and the things that money can buy, but it's good, too, to check up once in a while and make sure that you haven't lost the things that money can't buy.” —George Horace Lorimer",
    "“There are two ways of spreading light: to be the candle or the mirror that reflects it.” —Edith Wharton",
    "“There is nothing like returning to a place that remains unchanged to find the ways in which you yourself have altered.” —Nelson Mandela",
    "“When we seek for connection, we restore the world to wholeness. Our seemingly separate lives become meaningful as we discover how truly necessary we are to each other.” —Margaret Wheatley",
    "“A clear and innocent conscience fears nothing.” —Elizabeth I",
    "“Failure is often that early morning hour of darkness which precedes the dawning of the day of success.” —Leigh Mitchell Hodges",
    "“Run with your head in the first two thirds of a race and with your heart the final third.” —Jack Daniels",
    "“The truth is incontrovertible. Malice may attack it, ignorance may deride it, but in the end, there it is.” —Winston Churchill",
    "“Adventure is worthwhile in itself.” —Amelia Earhart",
    "“Spread love everywhere you go. Let no one ever come to you without leaving happier.” —Mother Teresa",
    "“Fortune does not change men, it unmasks them.” —Suzanne Necker",
    "“Any activity becomes creative when the doer cares about doing it right, or better.” —John Hoyer Updike",
    "“Don’t be afraid your life will end; be afraid that it will never begin.” —Grace Hansen",
    "“There is no shortcut to life. To the end of our days, life is a lesson imperfectly learned.” —Harrison Salisbury",
    "“The fragrance always stays in the hand that gives the rose.” —Hada Bejar",
    "“The most significant change in a person's life is a change of attitude. Right attitudes produce right actions.” —William J. Johnston",
    "“I don't have to be what you want me to be.” —Muhammad Ali",
    "“Sometimes we stare so long at a door that is closing that we see too late the one that is open.” —Alexander Graham Bell",
    "“The best leader does not ask people to serve him, but the common end. The best leader has not followers, but men and women working with him.” —Mary Parker Follett",
    "“To me, good health is more than just exercise and diet. It’s really a point of view and a mental attitude you have about yourself.” —Angela Lansbury",
    "“What counts is not necessarily the size of the dog in the fight - it's the size of the fight in the dog” —Dwight D. Eisenhower",
    "“If you watch how nature deals with adversity, continually renewing itself, you can’t help but learn.” —Bernie S. Siegel",
    "“The man who promises everything is sure to fulfil nothing, and everyone who promises too much is in danger of using evil means in order to carry out his promises.” —Carl Jung",
    "“We cannot solve problems with the kind of thinking we employed when we came up with them.” — Albert Einstein",
    "“He that climbs the tall tree has won the right to the fruit.” —Walter Scott...........Tomorrow the quotes will reset back <3 thanks for subscribing",
]
